version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

  postgres:
    image: postgres:latest
    container_name: my_posgres_container
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5433:5432

volumes:
  redis-data:

networks:
  redis-network: